plugins {
    id "java"
    id("io.github.sgtsilvio.gradle.maven-central-publishing") version "0.5.0"
    id("io.github.sgtsilvio.gradle.metadata") version "0.7.0"
    id "java-library"
    id "signing"
}

group = rootProject.maven_group
version = rootProject.version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(rootProject.java_version))
    withSourcesJar()
    withJavadocJar()
}

repositories {
}

dependencies {
    implementation 'com.networknt:json-schema-validator:1.5.1'
    
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.1'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.17.1'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.17.1'

    implementation "commons-io:commons-io:2.18.0"
    implementation 'com.google.guava:guava:33.3.1-jre'
}

tasks.withType(Jar) {
    zip64 = true
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId rootProject.maven_group
            artifactId project.name
            version project.version

            pom {
                description = "Library"
                url = "https://github.com/projectAccounth/enchantment_tweaks"
                licenses {
                    license {
                        name = 'GNU LGPLv3'
                        url = 'http://www.gnu.org/licenses'
                    }
                }
                developers {
                    developer {
                        id = 'not_thefirst'
                        name = 'not_thefirst'
                    }
                }
                scm {
                    connection = "scm:git:git://://github.com/projectAccounth/enchantment_tweaks.git"
                    developerConnection = "scm:git:ssh://://github.com/projectAccounth/enchantment_tweaks.git"
                    url = "https://github.com/projectAccounth/enchantment_tweaks"
                }
            }
        }
    }
}

signing {
    def signingKey = System.getenv("GPG_SIGNING_KEY")
    def signingPassword = System.getenv("GPG_PASSPHRASE")

    if (signingKey != null) {
        byte[] decodedKey = signingKey.decodeBase64()
        useInMemoryPgpKeys(new String(decodedKey), signingPassword)
        sign publishing.publications.mavenJava
    }
}
